core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'File System'
admin.site.site_title = 'File System'
admin.site.index_title = 'File System Dashboard'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('zones/', include('zones.urls')),
    path('files/', include('files.urls')),
    path('supports/', include('supports.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zones/urls.py
from django.urls import path, re_path
from zones.views import (ZoneCreateView, ZoneDeleteView, ZoneDeactivateView, DepartmentListCreateView, DepartmentDeactivateDeleteView)

app_name = 'zones'

urlpatterns = [
    path('', ZoneCreateView.as_view(), name='zone_create'),
    path('<int:id>/delete', ZoneDeleteView.as_view(), name='zone_delete'),
    path('<int:id>', ZoneDeactivateView.as_view(), name='zone_activate'),
    path('departments', DepartmentListCreateView.as_view(), name='zone_departments'),
    path('departments/<int:id>', DepartmentDeactivateDeleteView.as_view(), name='zone_departments_deactivate_delete'),
]

zones/models.py
from django.db import models


class Zone (models.Model):
    name = models.CharField(max_length=60, unique=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "zones"

    #Methods
    def __str__(self):
        return self.name

    @property
    def get_status(self):
        if self.is_active:
            return 'Deactivate'
        return 'Activate'


class Department (models.Model):
    zone = models.CharField(max_length=60)
    name = models.CharField(max_length=60, unique=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "departments"

    #Methods
    def __str__(self):
        return self.name

    @property
    def get_status(self):
        if self.is_active:
            return 'Deactivate'
        return 'Activate'

zones/forms.py
from django import forms
from zones.models import Zone, Department

class ZoneForm(forms.ModelForm):

    class Meta:
        model = Zone
        fields = ['name']


class DepartmentForm(forms.ModelForm):

    class Meta:
        model = Department
        fields = ['name', 'zone']

templates/users/zones/department.html
{% extends 'layouts/base.html' %}

{% block title %}Departments{% endblock title %}

{% load static %}

{% block content %}
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Home</span> - Departments</h4>
        </div>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
    
    <!-- Basic datatable -->
    <div class="card">
        <div class="card-header header-elements-inline">
            <button type="button" data-toggle="modal" data-target="#modal_add_form" class="btn btn-primary btn-sm btnAdd"><i class="fa fa-plus-circle"></i> Add New</button>
        </div>

        <div class="card-body table-responsive">
            <table class="table datatable-basic">
                <thead>
                    <tr class="text-primary">
                        <th>Created At</th>
                        <th>Department</th>
                        <th>Status</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for department in department_list %}
                    <tr class="record">
                        <td>{{ department.created_at }}</td>
                        <td>{{ department.name|upper }}</td>
                        <td>
                            {% if department.is_active %}
                            <span class="badge badge-success">Active</span>
                            {% else %}
                            <span class="badge badge-danger">Not Active</span>
                            {% endif %}
                        </td>
                        <td class="text-center">
                            <a href="{% url 'zones:zone_departments_deactivate_delete' department.id %}" data-token="{{ csrf_token }}" class="{%if department.is_active%}text-danger {%else%} text-success {%endif%} btnDeactivate mr-2" data-status="{{ department.get_status }}" title="{{ department.get_status }} {{ department.name|title }}"><i class="fa {% if department.is_active %} fa-ban {% else %} fa-check-circle {% endif %}"></i></a>
                            <a href="{% url 'zones:zone_departments_deactivate_delete' department.id %}" class="text-danger btnDelete" title="Delete {{ department.name|title }}"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!-- /basic datatable -->

    <!-- Vertical form modal -->
    <div id="modal_add_form" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add New Department</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <form action="{% url 'zones:zone_departments' %}" id="formDepartment">
                    <div class="modal-body">
                        {% csrf_token %}
                        <div class="form-group validate">
                            <label>Enter department name</label>
                            <input type="text" name="name" class="form-control" placeholder="eg:IT, Accounts, Procurement">
                            <span class="text-danger mySpan"></span>
                        </div> 
                        <input type="hidden" name="zone" readonly value="{{ request.user.zone }}">
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-link text-danger" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn bg-primary btn-sm btnSubmit">Submit <i class="icon-paperplane ml-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /vertical form modal -->

</div>
<!-- /content area -->
{% endblock content %}

{% block scripts %}
<script src="{% static 'assets/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'assets/js/pages/datatables_basic.js' %}"></script>
<script src="{% static 'assets/js/pages/zones/department.js' %}"></script>
{% endblock scripts %}

templates/users/zones/index.html
{% extends 'layouts/base.html' %}

{% block title %}Zones{% endblock title %}

{% load static %}

{% block content %}
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Home</span> - Zones</h4>
        </div>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
    
    <!-- Basic datatable -->
    <div class="card">
        <div class="card-header header-elements-inline">
            <button type="button" data-toggle="modal" data-target="#modal_add_form" class="btn btn-primary btn-sm btnAdd"><i class="fa fa-plus-circle"></i> Add New</button>
        </div>

        <div class="card-body table-responsive">
            <table class="table datatable-basic">
                <thead>
                    <tr class="text-primary">
                        <th>Created At</th>
                        <th>Zone</th>
                        <th>Status</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for zone in zone_list %}
                    <tr class="record">
                        <td>{{ zone.created_at }}</td>
                        <td>{{ zone.name|title }}</td>
                        <td>
                            {% if zone.is_active %}
                            <span class="badge badge-success">Active</span>
                            {% else %}
                            <span class="badge badge-danger">Not Active</span>
                            {% endif %}
                        </td>
                        <td class="text-center">
                            <a href="{% url 'zones:zone_activate' zone.id %}" class="{%if zone.is_active%}text-danger {%else%} text-success {%endif%} btnDeactivate mr-2" data-status="{{ zone.get_status }}" title="{{ zone.get_status }} {{ zone.name|title }}"><i class="fa {% if zone.is_active %} fa-ban {% else %} fa-check-circle {% endif %}"></i></a>
                            <a href="{% url 'zones:zone_delete' zone.id %}" class="text-danger btnDelete" title="Delete {{ zone.name|title }}"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!-- /basic datatable -->

    <!-- Vertical form modal -->
    <div id="modal_add_form" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add New Zone</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <form action="{% url 'zones:zone_create' %}" id="formZone">
                    <div class="modal-body">
                        <div class="form-group">
                            {% csrf_token %}
                            <div class="form-group validate">
                                <label>Enter zone name</label>
                                <input type="text" name="name" class="form-control" placeholder="Enter zone name">
                                <span class="text-danger mySpan"></span>
                            </div>                            
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-link text-danger" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn bg-primary btn-sm btnSubmit">Submit <i class="icon-paperplane ml-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /vertical form modal -->

</div>
<!-- /content area -->
{% endblock content %}

{% block scripts %}
<script src="{% static 'assets/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'assets/js/pages/datatables_basic.js' %}"></script>
<script src="{% static 'assets/js/pages/zones.js' %}"></script>
{% endblock scripts %}