accounts/urls.py
from django.urls import path, re_path
from accounts.views import (LoginView, LogoutView, ResetPasswordView, DashboardView, ProfileUpdateView, UserCreateView, UserListView, 
                            UserDeactivateView, UserDeleteView, UserDetailUpdateView, AccountTypeCreateView, ResetPasswordView,
                            AccountTypeDeactivateDeleteView, UserNotificationView, UserNotificationCount, ChangePasswordView, ProfilePhotoUpdateView)

app_name = 'accounts'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('reset-password', ResetPasswordView.as_view(), name='reset_password'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('profile', ProfileUpdateView.as_view(), name='profile'),
    path('users', UserCreateView.as_view(), name='users'),
    path('users/roles', AccountTypeCreateView.as_view(), name='users_types'),
    path('users/roles/<int:id>', AccountTypeDeactivateDeleteView.as_view(), name='users_types_deactivate_delete'),
    path('users-view', UserListView.as_view(), name='users_view'),
    path('users-view/<int:id>', UserDeactivateView.as_view(), name='users_deactivate_update'),
    path('users-view/<int:id>/delete', UserDeleteView.as_view(), name='users_delete'),
    path('users-view/<int:id>/detail', UserDetailUpdateView.as_view(), name='users_detail'),
    path('users-view/<int:id>/reset-password', ResetPasswordView.as_view(), name="reset_password"),

    path('users/notifications/counts', UserNotificationCount.as_view(), name='users_notifications_counts'),
    path('users/notifications', UserNotificationView.as_view(), name='users_notifications'),
    
    path('change-password', ChangePasswordView.as_view(), name="change_password"),
    path('update-profile-image', ProfilePhotoUpdateView.as_view(), name="update_image"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'File System'
admin.site.site_title = 'File System'
admin.site.index_title = 'File System Dashboard'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('zones/', include('zones.urls')),
    path('files/', include('files.urls')),
    path('supports/', include('supports.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path, re_path
from files.views import (FileCreateView, DepartmentGetView, ReceiverGetView, PendingFileListChangeStatusView, ReceivedFileListView, 
                        SentFileListView, ArchiveFileListView, ResendFileView, ForwardFileView, OldFileCreateView, OldFileView)

app_name = 'files'

urlpatterns = [
    path('', FileCreateView.as_view(), name='create'),
    path('deparments', DepartmentGetView.as_view(), name='department_get'),
    path('receivers', ReceiverGetView.as_view(), name='receiver_get'),
    path('view/pending', PendingFileListChangeStatusView.as_view(), name='view_pending'),
    path('view/received', ReceivedFileListView.as_view(), name='view_received'),
    path('view/sent', SentFileListView.as_view(), name='view_sent'),
    path('view/sent/resend', ResendFileView.as_view(), name='view_sent_resent'),
    path('view/forwarded', ForwardFileView.as_view(), name='view_forward'),

    path('archives', ArchiveFileListView.as_view(), name='archives'),
    path('old/add', OldFileCreateView.as_view(), name='old_files'),
    path('old/view', OldFileView.as_view(), name='view_old_files'),
]

files/models.py
from django.conf import settings
from django.db import models
from accounts.models import User

class File (models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="files", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    file = models.FileField(upload_to='files')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "files"

    #Methods
    def __str__(self):
        return self.name


class FileReciever (models.Model):
    PENDING = "pending"
    REJECTED = "rejected"
    ACCEPTED = "accepted"
    WORK_DONE = "work done"
    file = models.ForeignKey(File, related_name="file_receivers", on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name="receivers", on_delete=models.CASCADE)
    status = models.CharField(max_length=20, default=PENDING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "file_recivers"

    #Methods
    def __str__(self):
        return self.receiver.name


class ArchiveFile (models.Model):
    RESENT = 1
    REJECTED = 0
    ACCEPTED = 2
    FORWARDED = 3
    file = models.ForeignKey(File, related_name="archive_files", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="user_archive_files", on_delete=models.CASCADE)
    status = models.IntegerField(default=1)
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "archive_files"

    #Methods
    def __str__(self):
        return self.file


class ForwardFile (models.Model):
    file = models.ForeignKey(File, related_name="forward_files", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="user_forward_files", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "forward_files"

    #Methods
    def __str__(self):
        return self.file


class ForwardFileReceiver (models.Model):
    PENDING = 1
    REJECTED = 0
    ACCEPTED = 2
    forward_file = models.ForeignKey(ForwardFile, related_name="forward_file_receivers", on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name="forward_receivers", on_delete=models.CASCADE)
    status = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "forward_file_recivers"

    #Methods
    def __str__(self):
        return self.receiver.name



class OldFile (models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="old_files", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    type = models.CharField(max_length=20)
    file = models.FileField(upload_to='oldfiles')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "old_files"

    #Methods
    def __str__(self):
        return self.name

files/forms.py
from django import forms
from files.models import File, ArchiveFile, ForwardFile, OldFile

class FileCreateForm(forms.ModelForm):

    class Meta:
        model = File
        fields = ['user', 'name', 'file']


class ArchiveCreateForm(forms.ModelForm):

    class Meta:
        model = ArchiveFile
        fields = ['file', 'user', 'status']


class ForwardCreateForm(forms.ModelForm):

    class Meta:
        model = ForwardFile
        fields = ['file', 'user']


class OldFileCreateForm(forms.ModelForm):

    class Meta:
        model = OldFile
        fields = ['user', 'name', 'file']

files/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.template import loader
from django.db.models import Q
from django.db import transaction

from files.forms import FileCreateForm, ArchiveCreateForm, ForwardCreateForm, OldFileCreateForm
from files.models import File, ArchiveFile, ForwardFile, FileReciever, ForwardFileReceiver, OldFile
from zones.models import Zone, Department
from accounts.models import User

class FileCreateView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"
    form_class = FileCreateForm
    template_name = "users/files/index.html"

    def get(self, request, *args, **kwargs):
        zones = Zone.objects.all()
        context = {
            "zone_list": zones
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            form = self.form_class(request.POST, request.FILES)
            receivers = request.POST.getlist('receiver[]')
            if form.is_valid():
                if len(receivers) == 0:
                    return JsonResponse({"message": "No receivers selected"}) 
                else:
                    file = form.save()
                    for reciever in receivers:
                        FileReciever.objects.create(file=file, receiver_id=reciever)
                    return JsonResponse({"message": "success"}) 
            return JsonResponse({"message": form.errors})  
        return HttpResponse("Wrong request")


class DepartmentGetView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            zone = request.POST['zone']
            departments = Department.objects.filter(zone=zone).values('id', 'name')
            data = {
                'message': 'success',
                'data': list(departments)
            }
            return JsonResponse(data, safe=False)
        return JsonResponse({"message": "Wrong request"}) 


class ReceiverGetView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            zone = request.POST['zone']
            department = request.POST['department']
            if department == '':
                receivers = User.objects.filter(~Q(id=request.user.id), zone=zone,).values('id', 'name', 'account_type', 'zone')
            else:
                if request.user.account_type == User.ADMIN:
                    receivers = User.objects.filter(~Q(id=request.user.id), Q(department=department) | Q(department__isnull=True), Q(zone=User.ZONE_HEAD) | Q(zone=zone)).values('id', 'name', 'account_type', 'zone')
                else:
                    receivers = User.objects.filter(~Q(id=request.user.id), Q(department=department) | Q(department__isnull=True), zone=zone,).values('id', 'name', 'account_type', 'zone')
            data = {
                'message': 'success',
                'data': list(receivers)
            }
            return JsonResponse(data, safe=False) 
        return JsonResponse({"message": "Wrong request"}) 


class PendingFileListChangeStatusView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"
    template_name = "users/files/pending_file.html"

    def get(self, request, *args, **kwargs):
        files = FileReciever.objects.filter(receiver=request.user, status=FileReciever.PENDING)
        context = {
            "file_list": files
        }
        return render(request, self.template_name, context)

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            id = request.POST['file_id']
            file = get_object_or_404(FileReciever, pk=id)
            file.status = request.POST['status'] 
            file.save()
            ArchiveFile.objects.create(user=request.user, file=file.file, status=file.status)
            return JsonResponse({"message": "success"})  
        return JsonResponse({"message": "Wrong request"})


class ReceivedFileListView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"
    template_name = "users/files/receive_file.html"

    def get(self, request, *args, **kwargs):
        files = FileReciever.objects.filter(~Q(status=FileReciever.PENDING), receiver=request.user)
        forwarded = ForwardFileReceiver.objects.filter(receiver=request.user)
        zones = Zone.objects.all()
        context = {
            "file_list": files,
            "forward_list": forwarded,
            "zone_list": zones,
        }
        return render(request, self.template_name, context)


class SentFileListView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"
    template_name = "users/files/sent_file.html"

    def get(self, request, *args, **kwargs):
        files = File.objects.filter(user=request.user)
        context = {
            "file_list": files
        }
        return render(request, self.template_name, context)


class ArchiveFileListView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"
    template_name = "users/files/archive_file.html"

    def get(self, request, *args, **kwargs):
        ArchiveFile.objects.filter(file__user=request.user, is_read=False).update(is_read=True)
        if request.user.account_type == User.SUPER:
            files = ArchiveFile.objects.all()
            context = {
                "file_list": files
            }
        elif request.user.account_type == User.ADMIN:
            files = ArchiveFile.objects.filter(file__user__zone = request.user.zone)
            context = {
                "file_list": files
            }
        else:
            files = ArchiveFile.objects.filter(Q(user=request.user) | Q(file__user=request.user))
            context = {
                "file_list": files
            }
        return render(request, self.template_name, context)


class ResendFileView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"
    form_class = ArchiveCreateForm
    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            form = self.form_class(request.POST)
            if form.is_valid():
                form.save()
                return JsonResponse({'message':'success'})
            return JsonResponse({'message': form.errors})
        return HttpResponse('Wrong request')


class ForwardFileView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"
    template_name = "users/files/forward_file.html"
    form_class = ForwardCreateForm

    def get(self, request, *args, **kwargs):
        files = ForwardFile.objects.filter(user=request.user)
        context = {
            "file_list": files
        }
        return render(request, self.template_name, context)

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            form = self.form_class(request.POST)
            receivers = request.POST.getlist('receiver[]')
            if form.is_valid():
                if len(receivers) == 0:
                    return JsonResponse({'message':'No receivers selected'})
                else:
                    file = form.save()
                    exist = 0
                    forwarded = 0
                    for receiver in receivers:
                        if ForwardFileReceiver.objects.filter(forward_file=file, receiver_id=receiver).exists():
                            exist += 1
                        else:
                            ForwardFileReceiver.objects.create(forward_file=file, receiver_id=receiver)
                            forwarded += 1
        
                    exist_message = '' if exist == 0 else f"Already forwarded to {exist} receiver(s)."
                    return JsonResponse({'message':'success', 'report':f"File dispatched to {len(receivers)} receiver(s). {forwarded} received. {exist_message}"})
            return JsonResponse({'message': form.errors})
        return HttpResponse('Wrong request')


class OldFileCreateView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"
    form_class = OldFileCreateForm
    template_name = "users/files/old_file.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            form = self.form_class(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return JsonResponse({"message": "success"}) 
            return JsonResponse({"message": form.errors})  
        return HttpResponse("Wrong request")


class OldFileView(LoginRequiredMixin, View):
    login_url = "accounts:login"
    redirect_field_name = "redirect_to"
    template_name = "users/files/view_old_files.html"

    def get(self, request, *args, **kwargs):
        files = OldFile.objects.all()
        context = {
            'file_list': files
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            id = request.POST['file']
            file = get_object_or_404(OldFile, pk=id)
            file.delete()
            return JsonResponse({"message": "success"}) 
        return HttpResponse("Wrong request")

templates/users/files/index.html
{% extends 'layouts/base.html' %}

{% block title %}New file{% endblock title %}

{% load static %}

{% block content %}
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Files</span> - Add New</h4>
        </div>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">

    <!-- Main charts -->
    <div class="row">
        <div class="col-sm-12 col-lg-6 offset-lg-3">

            <!-- Traffic sources -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h6 class="card-title">Create New File</h6>
                    <div class="header-elements"></div>
                </div>

                <div class="card-body py-0">
                    <form action="{% url 'files:create' %}" id="formFile" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="user" value="{{ user.id }}" readonly>
                        <div class="form-group validate">
                            <label>File Name</label>
                            <input type="text" name="name" class="form-control" placeholder="Enter file name">
                            <span class="text-danger mySpan"></span>
                        </div> 

                        <!-- <div class="form-group validate">
                            <label>File Type</label>
                            <select name="type" class="form-control">
                                <option value="">--Select--</option>
                                <option value="docx">Word</option>
                                <option value="pdf">PDF</option>
                                <option value="xlsx">Excel</option>
                                <option value="csv">CSV</option>
                                <option value="zip">ZIP Files</option>
                                <option value="rar">RAR Files</option>
                                <option value="image">Image(jpg, jpeg)</option>
                            </select> 
                            <span class="text-danger mySpan"></span>
                        </div>  -->
                        <div class="form-group validate">
                            <label>File (<i class="text-danger" style="font-size: 10px;">500MB max file size</i>)</label>
                            <input type="file" name="file" id="upfile" class="form-control">
                            <span class="text-danger mySpan"></span>
                        </div> 
                        
                        <div class="form-group validate">
                            <label>Zone</label>
                            <select name="zone" class="form-control" data-url="{% url 'files:department_get' %}" data-token="{{ csrf_token }}" data-type="{{ user.account_type }}"  data-surl="{% url 'files:receiver_get' %}">
                                <option value="">--Select--</option>
                                {% for zone in zone_list %}
                                <option value="{{ zone.name }}">{{ zone.name|title }}</option>
                                {% endfor %}
                            </select> 
                            <span class="text-danger mySpan"></span>
                        </div> 
                       
                        {% if user.account_type != user.SUPER %}
                        <div class="form-group validate">
                            <label>Department</label>
                            <select name="department" class="form-control" data-url="{% url 'files:receiver_get' %}" data-token="{{ csrf_token }}">
                                <option value="" class="after">--Select--</option>
                            </select> 
                            <span class="text-danger mySpan"></span>
                        </div> 
                        {% endif %}

                        <div class="form-group validate">
                            <label>Receiver(s)</label>
                            <select name="receiver[]" multiple="multiple" data-placeholder="Select your receivers" class="form-control form-control-select2-icons" data-fouc>
                                <option value="" class="after">--Select--</option>
                            </select> 

                            <span class="text-danger mySpan"></span>
                        </div> 
                        
                        <div class="form-group">
                            <button type="submit" class="btn bg-primary btn-sm btnSubmit">Submit <i class="fa fa-dot-circle font-size-sm ml-2"></i></button>
                        </div> 
                    </form>
                </div>

            </div>
            <!-- /traffic sources -->

        </div>
    </div>
    <!-- /main charts -->

</div>
<!-- /content area -->
{% endblock content %}

{% block scripts %}
<script src="{% static 'assets/js/pages/files/files.js' %}"></script>
<script src="{% static 'assets/js/plugins/forms/selects/select2.min.js' %}"></script>
<script>
    function iconFormat(icon) {
        var originalOption = icon.element;
        if (!icon.id) { return icon.text; }
        var $icon = "<i class='icon-" + $(icon.element).data('icon') + "'></i>" + icon.text;

        return $icon;
    }

    $('.form-control-select2-icons').select2({
        templateResult: iconFormat,
        minimumResultsForSearch: Infinity,
        templateSelection: iconFormat,
        escapeMarkup: function(m) { return m; }
    });
</script>
{% endblock scripts %}

templates/users/files/receive_file.html
{% extends 'layouts/base.html' %}

{% block title %}View recieved files{% endblock title %}

{% load static %}

{% block content %}
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">File</span> - View Received Files</h4>
        </div>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">

    <div class="card">
        

        <div class="card-body table-responsive">
            <table class="table datatable-basic">
                <thead>
                    <tr class="text-primary">
                        <th>Created At</th>
                        <th>Sender</th>  
                        <th>File Name</th>
                        <th>File Type</th>
                        <th>Status</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for file in file_list %}
                    <tr class="record">
                        <td>{{ file.created_at }}</td>
                        <td>{{ file.file.user.name|title }}</td>  
                        <td>{{ file.file.name|title }}</td>
                        <td>{{ file.file.type|upper }}</td>
                        <td>
                            {% if file.file.status == file.file.ACCEPTED %}
                            <span class="badge badge-success">ACCEPTED TO ARCHIVE</span>
                            {% elif file.file.status == file.file.REJECTED %}
                            <span class="badge badge-danger">REJECTED BY RECEIVER</span>
                            {% endif %}
                        </td>
                        <td class="text-center">
                            <a href="{{ file.file.file.url }}" class="text-primary mr-3" title="Download {{ file.file.name|title }}"><i class="fa fa-download"></i></a>
                            <a href="#" class="text-purple btnForward" data-file="{{ file.file.id }}" title="Forward {{ file.file.name|title }}"><i class="fa fa-share"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% for file in forward_list %}
                    <tr class="record">
                        <td>{{ file.created_at }}</td>
                        <td>{{ file.forward_file.user.name|title }}</td>  
                        <td>{{ file.forward_file.file.name|title }}</td>
                        <td>{{ file.forward_file.file.type|upper }}</td>
                        <td>
                            <span class="badge badge-success">FORWARDED FILE</span>
                            <!-- {% if file.status == file.PENDING %}
                            <span class="badge badge-primary">PENDING</span>
                            {% elif file.status == file.ACCEPTED %}
                            <span class="badge badge-success">ACCEPTED TO ARCHIVE</span>
                            {% elif file.status == file.REJECTED %}
                            <span class="badge badge-danger">REJECTED TO SENDER</span>
                            {% endif %} -->
                        </td>
                        <td class="text-center">
                            <a href="{{ file.forward_file.file.file.url }}" class="text-primary mr-3" title="Download {{ file.forward_file.file.name|title }}"><i class="fa fa-download"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


     <!-- Vertical form modal -->
     <div id="forwardModal" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Forward File</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <form action="{% url 'files:view_forward' %}" id="formForward">
                    <div class="modal-body">
                        {% csrf_token %}
                        <input type="hidden" readonly name="file">
                        <input type="hidden" readonly name="user" value="{{ request.user.id }}">
                        <div class="form-group validate">
                            <label>Zone</label>
                            <select name="zone" class="form-control" data-url="{% url 'files:department_get' %}" data-token="{{ csrf_token }}">
                                <option value="">--Select--</option>
                                {% for zone in zone_list %}
                                <option value="{{ zone.name }}">{{ zone.name|title }}</option>
                                {% endfor %}
                            </select> 
                            <span class="text-danger mySpan"></span>
                        </div> 
                        <div class="form-group validate">
                            <label>Department</label>
                            <select name="department" class="form-control" data-url="{% url 'files:receiver_get' %}" data-token="{{ csrf_token }}">
                                <option value="" class="after">--Select--</option>
                            </select> 
                            <span class="text-danger mySpan"></span>
                        </div> 

                        <div class="form-group validate">
                            <label>Receiver(s)</label>
                            <!-- <select name="receiver" class="form-control">
                                <option value="" class="after">--Select--</option>
                            </select>  -->
                            <select name="receiver[]" multiple="multiple" data-placeholder="Select your receivers" class="form-control form-control-select2-icons" data-fouc>
                                <option value="" class="after">--Select--</option>
                            </select> 
                            <span class="text-danger mySpan"></span>
                        </div> 

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-link text-danger" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn bg-primary btn-sm btnSubmit">Forward <i class="icon-paperplane ml-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /vertical form modal -->

</div>
<!-- /content area -->
{% endblock content %}

{% block scripts %}
<script src="{% static 'assets/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'assets/js/pages/datatables_basic.js' %}"></script>
<script src="{% static 'assets/js/pages/files/files.js' %}"></script>
<script src="{% static 'assets/js/plugins/forms/selects/select2.min.js' %}"></script>
<script>
    function iconFormat(icon) {
        var originalOption = icon.element;
        if (!icon.id) { return icon.text; }
        var $icon = "<i class='icon-" + $(icon.element).data('icon') + "'></i>" + icon.text;

        return $icon;
    }

    $('.form-control-select2-icons').select2({
        templateResult: iconFormat,
        minimumResultsForSearch: Infinity,
        templateSelection: iconFormat,
        escapeMarkup: function(m) { return m; }
    });
</script>
{% endblock scripts %}