core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'File System'
admin.site.site_title = 'File System'
admin.site.index_title = 'File System Dashboard'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('zones/', include('zones.urls')),
    path('files/', include('files.urls')),
    path('supports/', include('supports.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supports/urls.py
from django.urls import path, re_path
from supports.views import (SupportCreateView)

app_name = 'supports'

urlpatterns = [
    path('', SupportCreateView.as_view(), name='create'),
]

supports/models.py
from django.conf import settings
from django.db import models

class Support (models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="supports", on_delete=models.CASCADE)
    type = models.CharField(max_length=30)
    subject = models.CharField(max_length=60)
    message = models.TextField()
    is_served = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "supports"

    #Methods
    def __str__(self):
        return self.subject

supports/forms.py
from django import forms
from supports.models import Support

class SupportCreateForm(forms.ModelForm):

    class Meta:
        model = Support
        fields = ['user', 'type', 'subject', 'message']

supports/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.db.models import Q

from supports.forms import SupportCreateForm
from supports.models import Support

class SupportCreateView(LoginRequiredMixin, View):
    form_class = SupportCreateForm
    template_name = "users/supports/index.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            form = self.form_class(request.POST)
            if form.is_valid():
                form.save()
                return JsonResponse({"message": "success"}) 
            return JsonResponse({"message": form.errors})  
        return HttpResponse("Wrong request")


# class DepartmentGetView(LoginRequiredMixin, View):

#     def post(self, request, *args, **kwargs):
#         if request.is_ajax():
#             zone = request.POST['zone']
#             departments = Department.objects.filter(zone=zone).values('id', 'name')
#             data = {
#                 'message': 'success',
#                 'data': list(departments)
#             }
#             return JsonResponse(data, safe=False)
#         return JsonResponse({"message": "Wrong request"}) 


# class ReceiverGetView(LoginRequiredMixin, View):

#     def post(self, request, *args, **kwargs):
#         if request.is_ajax():
#             zone = request.POST['zone']
#             department = request.POST['department']
#             receivers = User.objects.filter(~Q(id=request.user.id), Q(department=department) | Q(department__isnull=True), zone=zone,).values('id', 'name', 'account_type')
#             data = {
#                 'message': 'success',
#                 'data': list(receivers)
#             }
#             return JsonResponse(data, safe=False) 
#         return JsonResponse({"message": "Wrong request"}) 


# class PendingFileListChangeStatusView(LoginRequiredMixin, View):
#     template_name = "users/files/pending_file.html"

#     def get(self, request, *args, **kwargs):
#         files = File.objects.filter(receiver=request.user, status=File.PENDING)
#         context = {
#             "file_list": files
#         }
#         return render(request, self.template_name, context)

#     @transaction.atomic
#     def post(self, request, *args, **kwargs):
#         if request.is_ajax():
#             id = request.POST['file_id']
#             file = get_object_or_404(File, pk=id)
#             file.status = request.POST['status'] 
#             file.save()
#             ArchiveFile.objects.create(user=request.user, file=file, status=file.status)
#             return JsonResponse({"message": "success"})  
#         return JsonResponse({"message": "Wrong request"})


# class ReceivedFileListView(LoginRequiredMixin, View):
#     template_name = "users/files/receive_file.html"

#     def get(self, request, *args, **kwargs):
#         files = File.objects.filter(~Q(status=File.PENDING), receiver=request.user)
#         context = {
#             "file_list": files
#         }
#         return render(request, self.template_name, context)


# class SentFileListView(LoginRequiredMixin, View):
#     template_name = "users/files/sent_file.html"

#     def get(self, request, *args, **kwargs):
#         files = File.objects.filter(user=request.user)
#         context = {
#             "file_list": files
#         }
#         return render(request, self.template_name, context)


# class ArchiveFileListView(LoginRequiredMixin, View):
#     template_name = "users/files/archive_file.html"

#     def get(self, request, *args, **kwargs):
#         ArchiveFile.objects.filter(file__user=request.user, is_read=False).update(is_read=True)
#         files = ArchiveFile.objects.filter(Q(file__user=request.user) | Q(file__receiver=request.user))
#         context = {
#             "file_list": files
#         }
#         return render(request, self.template_name, context)


# class ResendFileView(LoginRequiredMixin, View):
#     form_class = ArchiveCreateForm
#     def post(self, request, *args, **kwargs):
#         if request.is_ajax():
#             form = self.form_class(request.POST)
#             if form.is_valid():
#                 form.save()
#                 return JsonResponse({'message':'success'})
#             return JsonResponse({'message': form.errors})
#         return HttpResponse('Wrong request')

templates/users/supports/index.html
{% extends 'layouts/base.html' %}

{% block title %}Create support{% endblock title %}

{% load static %}

{% block content %}
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Support</span> - Create New</h4>
        </div>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">

    <!-- Main charts -->
    <div class="row">
        <div class="col-sm-12 col-lg-6 offset-lg-3">

            <!-- Traffic sources -->
            <div class="card">
                <div class="card-header header-elements-inline">
                    <h6 class="card-title">Create Support</h6>
                    <div class="header-elements"></div>
                </div>

                <div class="card-body py-0">
                    <form action="{% url 'supports:create' %}" id="formAdd">
                        {% csrf_token %}
                        <input type="hidden" name="user" readonly value="{{ request.user.id }}">
                        <div class="form-group validate">
                            <label>Support Type</label>
                            <select name="type" class="form-control">
                                <option value="">--Select--</option>
                                <option value="account">Account</option>
                                <option value="file">Files</option>
                            </select> 
                            <span class="text-danger mySpan"></span>
                        </div> 

                        <div class="form-group validate">
                            <label>Message</label>
                            <input type="text" name="subject" class="form-control" placeholder="Enter subject">
                            <span class="text-danger mySpan"></span>
                        </div> 

                        <div class="form-group validate">
                            <label>Message</label>
                            <textarea rows="5" name="message" class="form-control" placeholder="Write your problem"></textarea>
                            <span class="text-danger mySpan"></span>
                        </div> 

                        <div class="form-group">
                            <button type="submit" class="btn bg-primary btn-sm btnSubmit">Submit <i class="fa fa-dot-circle font-size-sm ml-2"></i></button>
                        </div> 
                    </form>
                </div>

            </div>
            <!-- /traffic sources -->

        </div>
    </div>
    <!-- /main charts -->

</div>
<!-- /content area -->
{% endblock content %}

{% block scripts %}
<script src="{% static 'assets/js/pages/supports/support.js' %}"></script>
{% endblock scripts %}