accounts/urls.py
from django.urls import path, re_path
from accounts.views import (LoginView, LogoutView, ResetPasswordView, DashboardView, ProfileUpdateView, UserCreateView, UserListView, 
                            UserDeactivateView, UserDeleteView, UserDetailUpdateView, AccountTypeCreateView, ResetPasswordView,
                            AccountTypeDeactivateDeleteView, UserNotificationView, UserNotificationCount, ChangePasswordView, ProfilePhotoUpdateView)

app_name = 'accounts'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('reset-password', ResetPasswordView.as_view(), name='reset_password'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('profile', ProfileUpdateView.as_view(), name='profile'),
    path('users', UserCreateView.as_view(), name='users'),
    path('users/roles', AccountTypeCreateView.as_view(), name='users_types'),
    path('users/roles/<int:id>', AccountTypeDeactivateDeleteView.as_view(), name='users_types_deactivate_delete'),
    path('users-view', UserListView.as_view(), name='users_view'),
    path('users-view/<int:id>', UserDeactivateView.as_view(), name='users_deactivate_update'),
    path('users-view/<int:id>/delete', UserDeleteView.as_view(), name='users_delete'),
    path('users-view/<int:id>/detail', UserDetailUpdateView.as_view(), name='users_detail'),
    path('users-view/<int:id>/reset-password', ResetPasswordView.as_view(), name="reset_password"),

    path('users/notifications/counts', UserNotificationCount.as_view(), name='users_notifications_counts'),
    path('users/notifications', UserNotificationView.as_view(), name='users_notifications'),
    
    path('change-password', ChangePasswordView.as_view(), name="change_password"),
    path('update-profile-image', ProfilePhotoUpdateView.as_view(), name="update_image"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'File System'
admin.site.site_title = 'File System'
admin.site.index_title = 'File System Dashboard'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('zones/', include('zones.urls')),
    path('files/', include('files.urls')),
    path('supports/', include('supports.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
from django.urls import path, re_path
from files.views import (FileCreateView, DepartmentGetView, ReceiverGetView, PendingFileListChangeStatusView, ReceivedFileListView, 
                        SentFileListView, ArchiveFileListView, ResendFileView, ForwardFileView, OldFileCreateView, OldFileView)

app_name = 'files'

urlpatterns = [
    path('', FileCreateView.as_view(), name='create'),
    path('deparments', DepartmentGetView.as_view(), name='department_get'),
    path('receivers', ReceiverGetView.as_view(), name='receiver_get'),
    path('view/pending', PendingFileListChangeStatusView.as_view(), name='view_pending'),
    path('view/received', ReceivedFileListView.as_view(), name='view_received'),
    path('view/sent', SentFileListView.as_view(), name='view_sent'),
    path('view/sent/resend', ResendFileView.as_view(), name='view_sent_resent'),
    path('view/forwarded', ForwardFileView.as_view(), name='view_forward'),

    path('archives', ArchiveFileListView.as_view(), name='archives'),
    path('old/add', OldFileCreateView.as_view(), name='old_files'),
    path('old/view', OldFileView.as_view(), name='view_old_files'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.crypto import get_random_string


class MyUserManager(BaseUserManager):
    def create_user(self, email, name, account_type, zone, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not name:
            raise ValueError('Users must have name')
        if not zone:
            raise ValueError('Users must have account type')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
            account_type=account_type,
            zone=zone,
        )

        user.is_active = True
        user.is_admin = False
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, account_type, zone, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            name=name,
            account_type=account_type,
            password=password,
            zone=zone,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    SUPER = 'super'
    ADMIN = 'admin'
    ZONE_HEAD = 'head'
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=60)
    gender = models.CharField(max_length=10, null=True)
    phone = models.CharField(max_length=15, unique=True)
    zone = models.CharField(max_length=100, null=True)
    department = models.CharField(max_length=100, null=True)
    account_type = models.CharField(max_length=20, default='super')
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_active = models.BooleanField(default=True)
    owner = models.BigIntegerField(default=0)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name','account_type','zone',]

    objects = MyUserManager()

    class Meta:
        db_table = "account_users"
        indexes = [models.Index(fields=['zone']), models.Index(fields=['owner'])]

    def __str__(self):
        return f"{self.email}"

    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

    @property
    def get_random_password(self):
        return get_random_string(length=6)

    @property
    def get_status(self):
        if self.is_active:
            return 'Deactivate'
        return 'Activate'



class UserImage (models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name="user_image", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="users", null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "user_images"

    #Methods
    def __str__(self):
        return f"{self.user}"


    @property
    def get_user_image(self):
        if self.image:
            return self.image.url
        return 'assets/images/user.svg'


class AccountType (models.Model):
    name = models.CharField(max_length=60, unique=True)
    zone = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #Metadata
    class Meta :
        db_table = "account_types"

    #Methods
    def __str__(self):
        return self.name

    @property
    def get_status(self):
        if self.is_active:
            return 'Deactivate'
        return 'Activate'

accounts/forms.py
from django.contrib.auth import authenticate
from django import forms
from accounts.models import User, UserImage, AccountType

class LoginForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['email', 'password']

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login credentials.")

class RegisterUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'name', 'gender', 'phone', 'account_type', 'zone', 'department', 'password', 'owner']

class RegisterAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'name', 'gender', 'phone', 'account_type', 'zone', 'password', 'owner']

class UserUpdateForm(forms.Form):
    email = forms.EmailField(max_length=255)
    name = forms.CharField(max_length=60)
    gender = forms.CharField(max_length=10)
    phone = forms.CharField(max_length=15)
    account_type = forms.CharField(max_length=20)
    zone = forms.CharField(max_length=100)
    department = forms.CharField(max_length=100)

class AdminUpdateForm(forms.Form):
    email = forms.EmailField(max_length=255)
    name = forms.CharField(max_length=60)
    gender = forms.CharField(max_length=10)
    phone = forms.CharField(max_length=15)
    account_type = forms.CharField(max_length=20)
    zone = forms.CharField(max_length=100)

class UserImageForm(forms.ModelForm):

    class Meta:
        model = UserImage
        fields = ['image']


# class FileCreateForm(forms.ModelForm):

#     class Meta:
#         model = File
#         # fields = ['image']

class AccountTypeForm(forms.ModelForm):

    class Meta:
        model = AccountType
        fields = ['name', 'zone']


class SetPasswordForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    # password2 = forms.CharField(label='Password2', widget=forms.PasswordInput)

    # def clean(self):
    #     if 'password' in self.cleaned_data and 'password2' in self.cleaned_data:
    #         if self.cleaned_data['password1'] != self.cleaned_data['password2']:
    #             raise forms.ValidationError(_("The two password fields did not match."))
    #     return self.cleaned_data 

    class Meta:
        model = User
        fields = ["password"]


class ProfileUpdateForm(forms.Form):
    email = forms.EmailField(max_length=255)
    name = forms.CharField(max_length=60)
    gender = forms.CharField(max_length=10)
    phone = forms.CharField(max_length=15)

templates/users/accounts/account_type.html
{% extends 'layouts/base.html' %}

{% block title %}Roles{% endblock title %}

{% load static %}

{% block content %}
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Home</span> - Roles</h4>
        </div>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">
    
    <!-- Basic datatable -->
    <div class="card">
        <div class="card-header header-elements-inline">
            <button type="button" data-toggle="modal" data-target="#modal_add_form" class="btn btn-primary btn-sm btnAdd"><i class="fa fa-plus-circle"></i> Add New</button>
        </div>

        <div class="card-body table-responsive">
            <table class="table datatable-basic">
                <thead>
                    <tr class="text-primary">
                        <th>Created At</th>
                        <th>Type</th>
                        <th>Status</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for type in type_list %}
                    <tr class="record">
                        <td>{{ type.created_at }}</td>
                        <td>{{ type.name|title }}</td>
                        <td>
                            {% if type.is_active %}
                            <span class="badge badge-success">Active</span>
                            {% else %}
                            <span class="badge badge-danger">Not Active</span>
                            {% endif %}
                        </td>
                        <td class="text-center">
                            <a href="{% url 'accounts:users_types_deactivate_delete' type.id %}" data-token="{{ csrf_token }}" class="{%if type.is_active%}text-danger {%else%} text-success {%endif%} btnDeactivate mr-2" data-status="{{ type.get_status }}" title="{{ type.get_status }} {{ type.name|title }}"><i class="fa {% if type.is_active %} fa-ban {% else %} fa-check-circle {% endif %}"></i></a>
                            <a href="{% url 'accounts:users_types_deactivate_delete' type.id %}" class="text-danger btnDelete" title="Delete {{ type.name|title }}"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!-- /basic datatable -->

    <!-- Vertical form modal -->
    <div id="modal_add_form" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add New Account Type</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <form action="{% url 'accounts:users_types' %}" id="formAccountType">
                    <div class="modal-body">
                        {% csrf_token %}
                        <div class="form-group validate">
                            <label>Enter account type</label>
                            <input type="text" name="name" class="form-control" placeholder="eg:secretary, admin, supervisor">
                            <span class="text-danger mySpan"></span>
                        </div>   
                        <input type="hidden" name="zone" readonly value="{{ request.user.zone }}">
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-link text-danger" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn bg-primary btn-sm btnSubmit">Submit <i class="icon-paperplane ml-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /vertical form modal -->

</div>
<!-- /content area -->
{% endblock content %}

{% block scripts %}
<script src="{% static 'assets/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'assets/js/pages/datatables_basic.js' %}"></script>
<script src="{% static 'assets/js/pages/accounts/account_type.js' %}"></script>
{% endblock scripts %}

templates/users/accounts/notifications.html
{% load static %}

<div class="dropdown-content-header">
    <span class="font-weight-semibold">Notifications</span>
    <a href="#" class="text-default"><i class="icon-bell2"></i></a>
</div>

<div class="dropdown-content-body dropdown-scrollable">
    <ul class="media-list">
        {% for pending in pending_notification_list %}
        <li class="media">
            <div class="mr-3 position-relative">
                <img src="{% if pending.file.user.user_image.image %} {{ pending.file.user.user_image.image.url }} {% else %} {% static 'assets/images/user.svg' %} {% endif %}" width="36" height="36" class="rounded-circle" alt="">
            </div>

            <div class="media-body">
                <div class="media-title"> 
                    <a href="{% url 'files:view_pending'  %}">
                        <span class="font-weight-semibold">{{ pending.file.user.name|title }} - {{ pending.file.user.department }}</span>
                        <span class="text-muted float-right font-size-sm">{{ pending.created_at|date:'F d, Y' }}</span>
                    </a>
                </div>

                <span class="text-muted">Sent a file ({{ pending.file.name }}) - <span class="text-primary small">PENDING</span></span>
            </div>
        </li>
        {% endfor %}
        {% for accepted in accepted_notification_list %}
        <li class="media">
            <div class="mr-3 position-relative">
                <img src="{% if accepted.user.user_image.image %} {{ accepted.user.user_image.image.url }} {% else %} {% static 'assets/images/user.svg' %} {% endif %}" width="36" height="36" class="rounded-circle" alt="">
            </div>

            <div class="media-body">
                <div class="media-title"> 
                    <a href="{% url 'files:archives' %}">
                        <span class="font-weight-semibold">{{ accepted.user.name|title }} - {{ accepted.user.department }}</span>
                        <span class="text-muted float-right font-size-sm">{{ accepted.created_at|date:'F d, Y' }}</span>
                    </a>
                </div>

                <span class="text-muted">Accepted a file ({{ accepted.file.name }}) - <span class="text-success small">ACCEPTED</span></span>
            </div>
        </li>
        {% endfor %}

        {% for rejected in rejected_notification_list %}
        <li class="media">
            <div class="mr-3 position-relative">
                <img src="{% if rejected.user.user_image.image %} {{ rejected.user.user_image.image.url }} {% else %} {% static 'assets/images/user.svg' %} {% endif %}" width="36" height="36" class="rounded-circle" alt="">
            </div>

            <div class="media-body">
                <div class="media-title"> 
                    <a href="{% url 'files:archives' %}">
                        <span class="font-weight-semibold">{{ rejected.user.name|title }} - {{ rejected.user.department }}</span>
                        <span class="text-muted float-right font-size-sm">{{ rejected.created_at|date:'F d, Y' }}</span>
                    </a>
                </div>

                <span class="text-muted">Rejected a file ({{ rejected.file.name }}) - <span class="text-danger small">REJECTED</span></span>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

templates/users/accounts/profile.html
{% extends 'layouts/base.html' %}

{% block title %}My profile{% endblock title %}

{% load static %}

{% block content %}
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Home</span> - My Profile</h4>
        </div>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">

    <!-- Inner container -->
    <div class="d-md-flex align-items-md-start">

        <!-- Left sidebar component -->
        <div class="sidebar sidebar-light bg-transparent sidebar-component sidebar-component-left wmin-300 border-0 shadow-0 sidebar-expand-md">

            <!-- Sidebar content -->
            <div class="sidebar-content">

                <!-- Navigation -->
                <div class="card">
                    <div class="card-body bg-indigo-400 text-center card-img-top" style="background-image: url({% static 'assets/images/backgrounds/panel_bg.png' %}); background-size: contain;">
                        <div class="card-img-actions d-inline-block mb-3">
                            <img class="img-fluid rounded-circle imgPreview" src="{% if request.user.user_image.image %} {{ request.user.user_image.image.url }} {% else %} {% static 'assets/images/user.svg' %} {% endif %}" width="170" height="170" alt="{{ request.user.name }}">
                            <div class="card-img-actions-overlay rounded-circle">
                                <a href="#" class="btn btn-outline bg-white text-white border-white border-2 btn-icon rounded-round btnUploadImage">
                                    <i class="icon-plus3"></i>
                                </a>
                            </div>
                        </div>

                        <h6 class="font-weight-semibold mb-0">{{ request.user.name|title }}</h6>
                        <span class="d-block opacity-75">{{ request.user.account_type|title }}</span>

                    </div>
                </div>
                <!-- /navigation -->

            </div>
            <!-- /sidebar content -->

        </div>
        <!-- /left sidebar component -->


        <!-- Right content -->
        <div class="tab-content w-100">
            <div class="tab-pane fade active show" id="profile">
                <!-- Profile info -->
                <div class="card">
                    <div class="card-header header-elements-inline">
                        <h5 class="card-title">Profile information</h5>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                                <a class="list-icons-item" data-action="reload"></a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <form action="{% url 'accounts:profile' %}" id="formUpdateProfile">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6 validate">
                                        <label>Email</label>
                                        <input type="email" readonly name="email" value="{{ request.user.email }}" class="form-control">
                                        <span class="text-danger mySpan"></span>
                                    </div>
                                    <div class="col-md-6 validate">
                                        <label>Full name</label>
                                        <input type="text" name="name" value="{{ request.user.name|title }}" class="form-control">
                                        <span class="text-danger mySpan"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label class="d-block">Gender</label>
                                        <div class="form-check form-check-inline">
                                            <label class="form-check-label">
                                                <input type="radio" class="form-check-input" value="male" name="gender" {% if request.user.gender == 'male' %}checked{% endif %}>
                                                Male
                                            </label>
                                        </div>
            
                                        <div class="form-check form-check-inline">
                                            <label class="form-check-label">
                                                <input type="radio" class="form-check-input" value="female" name="gender" {% if request.user.gender == 'female' %}checked{% endif %}>
                                                Female
                                            </label>
                                        </div>
                                        <br>
                                        <span class="text-danger mySpan"></span>
                                    </div>
                                    <div class="col-md-6 validate">
                                        <label>Phone Number</label>
                                        <input type="tel" value="{{ request.user.phone }}" name="phone" onkeypress="return isNumber(event)" class="form-control">
                                        <span class="text-danger mySpan"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary btnSubmit">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /profile info -->


            </div>
        </div>
        <!-- /right content -->

    </div>
    <!-- /inner container -->

    <!-- Basic modal -->
    <div id="uploadModal" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

               <form action="{% url 'accounts:update_image' %}" id="formUploadImage" enctype="multipart/form-data">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-group validate">
                        <label>Profile Photo</label>
                        <input type="file" name="image" class="form-control">
                        <span class="text-danger mySpan"></span>
                    </div> 
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-link text-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn bg-primary btn-sm btnUpload">Upload Photo</button>
                </div>
               </form>
            </div>
        </div>
    </div>
    <!-- /basic modal -->

</div>
<!-- /content area -->
{% endblock content %}

{% block scripts %}
<script src="{% static 'assets/js/pages/accounts/users.js' %}"></script>
{% endblock scripts %}

templates/users/accounts/user_table.html
{% extends 'layouts/base.html' %}

{% block title %}View users{% endblock title %}

{% load static %}

{% block content %}
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Home</span> - View Users</h4>
        </div>
    </div>
</div>
<!-- /page header -->


<!-- Content area -->
<div class="content">

    <div class="card">
        

        <div class="card-body table-responsive">
            <table class="table datatable-basic">
                <thead>
                    <tr class="text-primary">
                        <th>Email</th>
                        <th>Full Name</th>
                        <th>Gender</th>
                        <th>Phone</th>
                        <th>Zone</th>
                        {% if request.user.account_type == 'admin' %}
                        <th>Account Type</th>
                        {% endif %}
                        <th>Status</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in user_list %}
                    <tr class="record">
                        <td>{{ user.email }}</td>
                        <td>{{ user.name|title }}</td>
                        <td>{{ user.gender|title }}</td>
                        <td>{{ user.phone }}</td>
                        <td>{{ user.zone|title }}</td>
                        {% if request.user.account_type == 'admin' %}
                        <td>{{ user.account_type|title }}</td>
                        {% endif %}
                        <td>
                            {% if user.is_active %}
                            <span class="badge badge-success">Active</span>
                            {% else %}
                            <span class="badge badge-danger">Not Active</span>
                            {% endif %}
                        </td>
                        <td class="text-center">
                            <a href="{% url 'accounts:users_detail' user.id %}" class="text-primary mr-2"><i class="fa fa-eye"></i></a>
                            {% if user.account_type != 'admin' or request.user.account_type == 'super' %}
                            <a href="{% url 'accounts:users_deactivate_update' user.id %}" class="{%if user.is_active%}text-danger {%else%} text-success {%endif%} btnDeactivate mr-2" data-status="{{ user.get_status }}" title="{{ user.get_status }} {{ user.name|title }}"><i class="fa {% if user.is_active %} fa-ban {% else %} fa-check-circle {% endif %}"></i></a>
                            <a href="{% url 'accounts:users_delete' user.id %}" class="text-danger btnDelete" title="Delete {{ user.name|title }}"><i class="fa fa-trash"></i></a>                                
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
<!-- /content area -->
{% endblock content %}

{% block scripts %}
<script src="{% static 'assets/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'assets/js/pages/datatables_basic.js' %}"></script>
<script src="{% static 'assets/js/pages/accounts/users.js' %}"></script>
{% endblock scripts %}